name: Build Tauri App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc

    - name: Install Tauri CLI
      run: npm install -g @tauri-apps/cli

    - name: Build frontend
      run: npm run build

    - name: Build Tauri app
      run: tauri build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: My-Wallet-Windows
        path: src-tauri/target/release/bundle/
        retention-days: 30

    - name: Create release ZIP
      run: |
        cd src-tauri/target/release/bundle/
        Compress-Archive -Path msi/* -DestinationPath "My-Wallet-Windows-v0.1.0.zip" -Force

    - name: Upload release ZIP
      uses: actions/upload-artifact@v4
      with:
        name: My-Wallet-Windows-ZIP
        path: src-tauri/target/release/bundle/*.zip
        retention-days: 30

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-gnu

    - name: Install Tauri CLI
      run: npm install -g @tauri-apps/cli

    - name: Build frontend
      run: npm run build

    - name: Build Tauri app
      run: tauri build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: My-Wallet-Linux
        path: src-tauri/target/release/bundle/
        retention-days: 30

    - name: Create release ZIP
      run: |
        cd src-tauri/target/release/bundle/
        zip -r "My-Wallet-Linux-v0.1.0.zip" appimage/

    - name: Upload release ZIP
      uses: actions/upload-artifact@v4
      with:
        name: My-Wallet-Linux-ZIP
        path: src-tauri/target/release/bundle/*.zip
        retention-days: 30

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-apple-darwin

    - name: Install Tauri CLI
      run: npm install -g @tauri-apps/cli

    - name: Build frontend
      run: npm run build

    - name: Build Tauri app
      run: tauri build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: My-Wallet-macOS
        path: src-tauri/target/release/bundle/
        retention-days: 30

    - name: Create release ZIP
      run: |
        cd src-tauri/target/release/bundle/
        zip -r "My-Wallet-Mac-v0.1.0.zip" macos/

    - name: Upload release ZIP
      uses: actions/upload-artifact@v4
      with:
        name: My-Wallet-macOS-ZIP
        path: src-tauri/target/release/bundle/*.zip
        retention-days: 30 